##
##  ci.yml
##  Networker
##
##  Created by Ariel Elkin on 22/09/2020.
##  Copyright © 2020 TGR1.618 Ltd. All rights reserved.
##

name: CI

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint
        run: swiftformat --lint --swiftversion 5.5 .

      - name: Build
        run: swift build

      - name: Test
        run: swift test
